# Teonet Dockerfile

FROM gitlab.ksproject.org:5000/teonet/teonet
MAINTAINER Kirill Scherba <kirill@scherba.ru>

# Update (teohws and ...)
RUN apt-get update 

# Common dependence
#RUN apt-get install -y psmisc

# Install teohws
RUN apt-get install -y teohws
